### ISSUE TITLE
extra history state

### ISSUE THREAD

**Issue by dunaevai135** [yegorf1/yogurtthesite#1]
when you click on the link on the page to the same page, an extra history state is created
## Expected Behavior
do not produce navigation on history without necessity
![a_1](https://user-images.githubusercontent.com/11465382/50696334-32f73280-1050-11e9-9d01-ef98707baae6.png)
![a_2](https://user-images.githubusercontent.com/11465382/50696340-35598c80-1050-11e9-9dd9-8fbcdd1a6805.png)

## Current Behavior
Many same pages at history
![screenshot at 2019-01-04 18-29-52](https://user-images.githubusercontent.com/11465382/50696370-4a362000-1050-11e9-9191-1a73cd39fa1b.png)

> P.S. sorry for screenshots

**Comment by yegorf1** [comment]
Probably, the it's not a bug. It should reload page, but the problem is that it doesn't refresh page actually.

More info you can find [here](https://github.com/ReactTraining/history/issues/470).
